apply_scene:
  name: Apply Scene
  description: Apply colors from an image scene to a Chameleon configuration
  target:
    entity:
      domain: select
      integration: chameleon
  fields:
    scene_name:
      name: Scene Name
      description: Name of the scene (image) to apply
      required: true
      selector:
        text: {}

start_animation:
  name: Start Animation
  description: Enable animation mode and apply a scene
  target:
    entity:
      domain: select
      integration: chameleon
  fields:
    scene_name:
      name: Scene Name
      description: Name of the scene (image) to use for animation
      required: true
      selector:
        text: {}

stop_animation:
  name: Stop Animation
  description: Stop color animation
  target:
    entity:
      domain: switch
      integration: chameleon
